services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gamestore-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gamestore-frontend
    networks:
      - frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: gamestore-db
    restart: always
    environment:
      POSTGRES_USER: gamestore
      POSTGRES_PASSWORD: gamestore
      POSTGRES_DB: game-store
    networks:
      - backend
    ports:
      - "5435:5432"

  
networks:
    backend:
      driver: bridge
    
    frontend:
      driver: bridge
