services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: loja-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: loja-frontend
    networks:
      - frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: loja-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game-store
    networks:
      - backend
  
networks:
    backend:
      driver: bridge
    
    frontend:
      driver: bridge
